### ISSUE TITLE
TODO: Indexers

### ISSUE THREAD

**Issue by AeonLucid** [Cinemation/Cinemation#1]
Cinemation needs a way to search multiple torrent sites for torrents. Both public and private trackers will be supported. I will plan to support NZB.

# APIs

## Public Trackers
- [ ] rarbg.to - https://torrentapi.org/apidocs_v2.txt
- [ ] yts.ag - https://yts.ag/api

## Private Trackers
- [ ] MoreThanTV - https://www.morethan.tv/
- [ ] IPTorrents - https://iptorrents.com/

**Comment by d2dyno** [comment]
I would suggest implementing like 'TorrentPotato', so an application like Jackett can integrate with and you don't have to maintain the indexer code. That's for public trackers though.

**Comment by galli-leo** [comment]
@d2dyno Jackett also works for PrivateTrackers. I would appreciate adding TorrentPotato very much. (May do it myself if I find the time to do it)

**Comment by galli-leo** [comment]
I added the first implemenation for the TorrentPotato provider in pull request #2

**Comment by jlawrence11** [comment]
Can you add torrentz2.eu?
